apps/cms/__init__.py
# encoding: utf-8
# __init__.py.py by Anderson Huang at 2018/12/24 11:27
from .views import bp
import apps.cms.hooks

apps/cms/views.py
# encoding: utf-8
# views.py by Anderson Huang at 2018/12/24 11:28
from flask import (
    Blueprint,
    views,
    render_template,
    request, session,
    redirect,
    url_for,
    g,
)
from .forms import (
    LoginForm,
    ResetpwdForm,
    ResetEmailForm,
    AddBannerForm,
    UpdateBannerForm,
    AddBoardForm,
    UpdateBoardForm,
)
from ..models import BannerModel, BoardModel, PostModel, HighlightPostModel
from .models import CMSUser, CMSPermission
from .decorators import login_required, permission_required
from exts import db, mail
from flask_mail import Message
from utils import restful, zlcache
from tasks import send_mail
import config
import string
import random

bp = Blueprint('cms', __name__, url_prefix='/cms')


# cms后台主页视图函数
@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')  # 跳转到cms后台主页


# 注销视图函数
@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]  # 删除session中的用户id字串
    return redirect(url_for('cms.login'))  # 返回登陆页面


# 个人详情页面视图函数
@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


# 测试发送邮件视图
@bp.route('/email/')
@login_required
def send_email():
    message = Message('邮件发送', recipients=['huanganfa66@163.com'], body='测试')
    mail.send(message)
    return '邮件已发送成功！'


# 发送邮件验证码视图
@bp.route('/email_captcha/')
@login_required
def email_captcha():
    # /email_captcha/?email=xxx.@qq.com 获取到发送邮箱
    email = request.args.get('email')
    if not email:
        return restful.params_error('请传递邮箱参数！')

    # 随机生成6位验证码字串,大小写字母加上0-9数字
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))
    captcha = "".join(random.sample(source, 6))

    # 给获取到的新的邮箱发送邮件验证码
    # message = Message('知了论坛邮箱验证码', recipients=[email], body='你的验证码是：%s' % captcha)
    # try:
    #     mail.send(message)
    # except:
    #     return restful.server_error()

    # 修改为异步发送邮件
    try:
        send_mail.delay('知了论坛邮箱验证码', recipients=[email], body='你的验证码是：%s' % captcha)
    except:
        return restful.server_error()

    zlcache.set(email, captcha)  # 添加验证码缓存
    return restful.success()


# 帖子管理模块视图
@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html', posts=post_list)


# 添加加精帖子视图函数
@bp.route('/hpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def hpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    highlight = HighlightPostModel()
    highlight.post = post

    db.session.add(highlight)
    db.session.commit()
    return restful.success()


# 取消加精帖子视图函数
@bp.route('/uhpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def uhpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()


# 移除加精帖子视图函数
@bp.route('/dpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def dpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.params_error('请传入帖子id！')

    post = PostModel.query.get(post_id)
    if not post:
        return restful.params_error('没有这篇帖子！')

    db.session.delete(post)
    db.session.commit()
    return restful.success()


# 评论管理模块驶入
@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


# 板块管理模块视图
@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models = BoardModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)


# 添加板块视图
@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data

        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


# 更新板块视图
@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个板块！')
    else:
        return restful.params_error(message=form.get_error())


# 删除板块视图
@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.params_error('请输入板块id!')

    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个板块！')

    db.session.delete(board)
    db.session.commit()
    return restful.success()


# 前台用户管理模块视图
@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')


# CMS用户管理视图
@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


# CMS组管理视图
@bp.route('/croles/')
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


# CMS轮播图管理视图
@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).all()  # 获取所有的轮播图,降序排列
    return render_template('cms/cms_banners.html', banners=banners)


# cms添加轮播图视图
@bp.route('/abanner/', methods=['POST'])
@login_required
def abanner():
    form = AddBannerForm(request.form)  # 验证
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data

        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)  # 保存
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


# cms编辑更新轮播图视图
@bp.route('/ubanner/', methods=['POST'])
@login_required
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data

        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='没有这个轮播图！')
    else:
        return restful.params_error(message=form.get_error())


# cms删除轮播图视图函数
@bp.route('/dbanner/', methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message='请输入轮播图id！')

    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个轮播图！')

    db.session.delete(banner)
    db.session.commit()

    return restful.success()


# 登录类视图
class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data

            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id  # 指定用户id为固定的字串
                if remember:
                    # 如果设置session.permanent = True, 那么过期时间是31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或者密码错误')
        else:
            # print(form.errors)
            # message = form.errors.popitem()[1][0]  # 提取表单验证forms.py传递过来的消息
            message = form.get_error()  # 修改为使用父类的get_error()方法
            return self.get(message=message)


# 修改密码类视图
class ResetPwdView(views.MethodView):
    decorators = [login_required]  # 保证用户登陆

    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetpwdForm(request.form)  # 验证修改密码
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user  # 使用g对象传递用户对象
            if user.check_password(oldpwd):
                # 更新数据库中的密码
                user.password = newpwd
                db.session.commit()
                # 返回json数据
                # return jsonify({"code": 200, "message": ""})
                return restful.success()
            else:
                # return jsonify({"code": 400, "message": "旧密码输入错误"})

apps/front/views.py
# encoding: utf-8
# views.py by Anderson Huang at 2018/12/24 11:28
from flask import (
    Blueprint,
    views,
    render_template,
    request,
    session,
    url_for,
    g,
    abort,
    redirect
)
from .forms import (
    SignupForm,
    SigninForm,
    AddPostForm,
    AddCommentForm
)
from utils import restful, safeutils
from .models import FrontUser
from ..models import BannerModel, BoardModel, PostModel, CommentModel, HighlightPostModel
from exts import db
from .decorators import login_required
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy.sql import func
import config

bp = Blueprint('front', __name__)


# 主页视图汉纳树
@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)  # 排序因子
    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)  # 降序
    boards = BoardModel.query.all()  # 板块
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE

    if sort == 1:
        # 默认按照创建时间倒序排列
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精时间倒序排列
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞数量倒序排序 由于还没有添加点赞功能，暂时按照默认排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论数量倒序排列
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    if board_id:  # 特定板块的帖子
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:  # 全部帖子
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0,
                            inner_window=2)  # 分页器
    context = {  # 上下文
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort,
    }
    return render_template('front/front_index.html', **context)


# 添加帖子视图
@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data

            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')

            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user  # 传递前台用户
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())


# 帖子详情视图函数
@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)


# 添加评论视图函数
@bp.route('/acomment/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这篇帖子！')
    else:
        return restful.params_error(form.get_error())


# 前台用户注销视图
@bp.route('/logout/')
@login_required
def logout():
    del session[config.FRONT_USER_ID]
    return redirect(url_for('front.signin'))


# 注册类视图
class SignupView(views.MethodView):
    def get(self):
        # 跳转到之前的页面,如果存在的话
        return_to = request.referrer
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        # 验证表单
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data

            # 创建新的前台用户
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())  # 打印出错误信息
            return restful.params_error(message=form.get_error())


# 前台登录类视图
class SigninView(views.MethodView):
    def get(self):
        # 跳转到之前的页面，如果有的话
        return_to = request.referrer
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        # 验证登录
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号码或密码错误！')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}轮播图管理{% endblock %}

{% block head %}
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ static('common/zlqiniu.js') }}"></script>
    <script src="{{ static('cms/js/cms_banners.js') }}"></script>
    <style>
        .top-box button {
            float: right;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="form-container" style="width: 1000px;">
        <div class="top-box" style="width: 100%;">
            <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
        </div>
        <table class="table table-bordered">
            <thread>
                <tr>
                    <th>名称</th>
                    <th>图片链接</th>
                    <th>跳转链接</th>
                    <th>优先级</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>
            </thread>
            <tbody>
            {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}"
                    data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn" style="margin-top:5px;">删除</button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <!-- Modal -->
        <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">轮播图</h4>
                    </div>
                    <div class="modal-body">
                        <form action="" class="form-horizontal">
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">名称：</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">图片：</label>
                                <div class="col-sm-7">
                                    <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                                </div>
                                <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">跳转：</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">权重：</label>
                                <div class="col-sm-10">
                                    <input type="number" class="form-control" name="priority" placeholder="优先级">
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/cms/cms_base.html
{% from 'common/_macros.html'import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {#  加载公共头文件 必须先加载 后面有继承关系  #}
    {% include 'common/_heads.html' %}
    {#  修改此处，引入css文件  #}
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='cms/css/cms_base.css') }}">#}
    <link rel="stylesheet" href="{{ static('cms/css/cms_base.css') }}">
    {#  修改此处，引入js文件  #}
    {#    <script src="{{ url_for('static', filename='cms/js/cms_base.js') }}"></script>#}
    <script src="{{ static('cms/js/cms_base.js') }}"></script>
    {# 加载公共头文件 #}
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
                <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="{{ url_for('cms.profile') }}">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                {#  实现前端展示用户权限列表功能  #}
                {% set cms_user = g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if cms_user.has_permission(CMSPermission.POSTER) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.COMMENTER) %}
                    <li class="comment-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.FRONTUSER) %}
                    <li class="nav-group fuser-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
                {% endif %}
                {% if cms_user.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                {% endif %}
                {% if cms_user.is_developer %}
                    <li class="crole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}板块管理{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/cms_boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" style="float: right;" id="add-board-btn">添加新板块</button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>板块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>0</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-default btn-xs edit-board-btn">编辑</button>
                    <button class="btn btn-danger btn-xs delete-board-btn">删除</button>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}评论管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    评论管理页面
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS组管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    CMS组管理页面
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}CMS组管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    CMS组管理页面
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    知了课堂CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到知了课堂CMS管理系统
{% endblock %}

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from 'common/_macros.html' import static %}

{% block title %}帖子管理{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/cms_posts.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>标题</th>
            <th>发布时间</th>
            <th>板块</th>
            <th>作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                <td><a target="_blank" href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                </td>
                <td>{{ post.create_time }}</td>
                <td>{{ post.board.name }}</td>
                <td>{{ post.author.username }}</td>
                <td>
                    {% if post.highlight %}
                        <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                    {% else %}
                        <button class="btn btn-default btn-xs highlight-btn">加精</button>
                    {% endif %}
                    <button class="btn btn-danger btn-xs delete-post-btn">移除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}